# Generated by Django 4.2 on 2024-03-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_projectfile_projectcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects_app.baseproject'),
        ),
    ]
