# Generated by Django 4.2 on 2024-04-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_alter_projectcomment_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'ordering': ['created_at']},
        ),
    ]
