# Generated by Django 4.2 on 2024-04-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0005_baseproject_created_at_baseproject_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='title',
            field=models.CharField(default='file', max_length=25),
            preserve_default=False,
        ),
    ]
