# Generated by Django 4.2 on 2024-04-08 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects_app', '0008_alter_project_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to={'client__is_main': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
