# Generated by Django 5.0.2 on 2024-03-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='company',
            new_name='client',
        ),
    ]
