# Generated by Django 4.2 on 2024-04-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_appuser_verification_code_alter_appuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='verification_code',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
