# Generated by Django 5.0.2 on 2024-03-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('street_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_main_company', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('postal_code', models.PositiveIntegerField()),
                ('telephone_number', models.PositiveIntegerField()),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telephone_code', models.PositiveIntegerField()),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients_app.municipality')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
