# Generated by Django 5.0.2 on 2024-03-10 08:41

import OPM_arch_Project.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='telephone_number',
            field=models.CharField(default=None, max_length=100, validators=[django.core.validators.MinLengthValidator(5), OPM_arch_Project.core.validators.check_only_digits]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='telephone_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2), OPM_arch_Project.core.validators.check_only_digits]),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='telephone_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5), OPM_arch_Project.core.validators.check_only_digits]),
        ),
    ]
