# Generated by Django 5.0.2 on 2024-03-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_rename_company_appuser_client'),
        ('clients_app', '0002_company_telephone_number_company_website_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Client',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='is_main_company',
            new_name='is_main',
        ),
    ]
